### ISSUE TITLE
Failure in startup because of missing required secret in Tomcat server.xml

### ISSUE THREAD

**Issue by joefutrelle** [axiom-data-science/docker-erddap#14]
Tomcat is encountering an error during startup:

```
erddap      | 23-Sep-2020 14:20:40.601 SEVERE [main] org.apache.catalina.core.StandardService.startInternal Failed to start connector [Connector[AJP/1.3-8009]]
erddap      |   org.apache.catalina.LifecycleException: Protocol handler start failed
erddap      |           at org.apache.catalina.connector.Connector.startInternal(Connector.java:1102)
erddap      |           at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
erddap      |           at org.apache.catalina.core.StandardService.startInternal(StandardService.java:440)
erddap      |           at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
erddap      |           at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:766)
erddap      |           at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
erddap      |           at org.apache.catalina.startup.Catalina.start(Catalina.java:688)
erddap      |           at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
erddap      |           at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
erddap      |           at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
erddap      |           at java.lang.reflect.Method.invoke(Method.java:498)
erddap      |           at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:342)
erddap      |           at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:473)
erddap      |   Caused by: java.lang.IllegalArgumentException: The AJP Connector is configured with secretRequired="true" but the secret attribute is either null or "". This combination is not valid.
erddap      |           at org.apache.coyote.ajp.AbstractAjpProtocol.start(AbstractAjpProtocol.java:274)
erddap      |           at org.apache.catalina.connector.Connector.startInternal(Connector.java:1100)
erddap      |           ... 12 more
```

It appears that the current version of Tomcat sets `secretRequired` to true, and if no secret is provided will refuse to start the AJP connector.

**Comment by kwilcox** [comment]
@joefutrelle Fixed in https://github.com/axiom-data-science/docker-erddap/commit/0be300073f3a6485f5295274c51ef0fad5d3b303, I can run it locally after build now. The upstream Tomcat image keeps changing and pushing over existing tag images. Not ideal. These types of bugs keep popping up and I'll just keep having to fix them when they do. Thanks for reporting!

It is building in CI now. When a new `latest` tag is available [here](https://hub.docker.com/r/axiom/docker-erddap/builds) you should be able to try it.

**Comment by kwilcox** [comment]
@joefutrelle can you confirm this is fixed?

**Comment by joefutrelle** [comment]
This is fixed. Thanks!
