### ISSUE TITLE
Failure: "_FileVisitor isn't a directory"

### ISSUE THREAD

**Issue by joefutrelle** [axiom-data-science/docker-erddap#16]
I'm having trouble running the container because the first request fails with this error message:

```
erddap      | ////**** ERD Low Level Startup
erddap      | localTime=2020-10-28T15:05:32+00:00
erddap      | erddapVersion=2.02
erddap      | Java 1.8.0_265 (64 bit, Oracle Corporation) on Linux (5.4.0-48-generic).
erddap      | MemoryInUse=   470 MB (highWaterMark=   470 MB) (Xmx ~= 4029 MB)
erddap      | logLevel=info: verbose=true reallyVerbose=false
erddap      | ERROR in File2.deleteIfOld: dir=/erddapData/dataset/_FileVisitor/ isn't a directory.
erddap      | bigParentDirectory=/erddapData/
erddap      | contextDirectory=/usr/local/tomcat/webapps/erddap/
erddap      | java.awt.HeadlessException
erddap      |  at gov.noaa.pfel.coastwatch.sgt.SgtUtil.isBufferedImageAccelerated(SgtUtil.java:368)
erddap      |  at gov.noaa.pfel.erddap.util.EDStatic.<clinit>(EDStatic.java:1574)
erddap      |  at gov.noaa.pfel.erddap.Erddap.<init>(Erddap.java:214)
```

Looking at the mounted volume on the host, ERDDAP has populated my bigParentDirectory with some files and directories, but `_FileVisitor` does not exist, and it looks like ERDDAP is trying to delete it and failing. Has anyone run into this problem? I suspect it may be some thorny host configuration issue having to do with uid/gid mapping and permissions.

**Comment by joefutrelle** [comment]
Looks like that error is innocuous and unrelated to the issue I had with accessing ERDDAP after startup--which was operator error on my part (I was using the default `setup.xml` which expects everything to be running on `localhost`)
