### ISSUE TITLE
java.lang.NoClassDefFoundError: com/amazonaws/AmazonServiceException

### ISSUE THREAD

**Issue by sccoos** [axiom-data-science/docker-erddap#25]
Hi,

I'm trying to run the GenerateDatasets.sh script using the ERDDAP 2.10 docker image, but I'm getting the errors below.  I see /usr/local/tomcat/webapps/erddap/WEB-INF/lib/aws-java-sdk.jar in the image and from there, I'm not sure what the problem might be.

Is anyone else seeing this?

$ docker --version
Docker version 20.10.3, build 48d30b5

$ docker run --rm -it   -v dev-erddap-data:/erddapData -v $(pwd)/logs:/erddapData/logs   axiom/docker-erddap:2.10   bash -c "cd webapps/erddap/WEB-INF/ && bash GenerateDatasetsXml.sh -verbose"

////**** ERD Low Level Startup
localTime=2021-02-09T18:43:11+00:00
erddapVersion=2.10
Java 1.8.0_265 (64 bit, Oracle Corporation) on Linux (3.10.0-1160.6.1.el7.x86_64).
MemoryInUse=    35 MB (highWaterMark=    35 MB) (Xmx ~= 958 MB)
ERROR during ERD Low Level Startup:
ERROR while reading /usr/local/tomcat/content/erddap/setup.xml: 
java.lang.NoClassDefFoundError: com/amazonaws/AmazonServiceException
 at gov.noaa.pfel.erddap.util.EDStatic.setLogLevel(EDStatic.java:3083)
 at gov.noaa.pfel.erddap.util.EDStatic.<clinit>(EDStatic.java:1522)
 at gov.noaa.pfel.erddap.GenerateDatasetsXml.<clinit>(GenerateDatasetsXml.java:44)
Caused by: java.lang.ClassNotFoundException: com.amazonaws.AmazonServiceException
 ... 3 more

Exception in thread "main" java.lang.ExceptionInInitializerError
	at gov.noaa.pfel.erddap.GenerateDatasetsXml.<clinit>(GenerateDatasetsXml.java:44)
Caused by: java.lang.RuntimeException: ERROR during ERD Low Level Startup:
ERROR while reading /usr/local/tomcat/content/erddap/setup.xml: 
java.lang.NoClassDefFoundError: com/amazonaws/AmazonServiceException
 at gov.noaa.pfel.erddap.util.EDStatic.setLogLevel(EDStatic.java:3083)
 at gov.noaa.pfel.erddap.util.EDStatic.<clinit>(EDStatic.java:1522)
 at gov.noaa.pfel.erddap.GenerateDatasetsXml.<clinit>(GenerateDatasetsXml.java:44)
Caused by: java.lang.ClassNotFoundException: com.amazonaws.AmazonServiceException
 ... 3 more

	at gov.noaa.pfel.erddap.util.EDStatic.<clinit>(EDStatic.java:3055)
	... 1 more

**Comment by kwilcox** [comment]
@sccoos this was a bug in ERDDAP 2.10, I am pushing a tagged `axiom/docker-erddap:2.11` now which fixes the issue!

**Comment by sccoos** [comment]
Thanks, Kyle!!

Vicky Rowley
SCCOOS DMAC
CCE LTER IM (Interim)
(858) 246-2623
vrowley@ucsd.edu   <==  For Zoom and/or Google Meet
https://sccoos.org
https://cce.lternet.edu
