### ISSUE TITLE
issues with config.sh

### ISSUE THREAD

**Issue by thogar-computer** [axiom-data-science/docker-erddap#44]
I was following the instructions within this git repo and It seems that I am having issues when i start trying to use the config.sh option. 

this simple example is failing;

```shell
docker run -p 8080:8080 -v C:\docker\erddap-docker-setup\config2.sh:/usr/local/tomcat/bin/config.sh -v C:\docker\volumes\erddap\BigDataDir:/erddapData  axiom/docker-erddap
```
here config2.sh only contains
```shell
ERDDAP_bigParentDirectory="/erddapData"
```
the container is built and starts running  but when you try and access the address http://127.0.0.1:8080/erddap an error is thrown

```shell
////**** EDStatic Low Level Startup
localTime=2022-03-30T12:40:47+00:00
erddapVersion=2.18
Java 1.8.0_322 (64 bit, Oracle Corporation) on Linux (5.10.16.3-microsoft-standard-WSL2).
MemoryInUse=   564 MB (highWaterMark=   564 MB) (Xmx ~= 4012 MB)
logLevel=info: verbose=true reallyVerbose=false
got bigParentDirectory from ERDDAP_bigParentDirectory
ERROR during EDStatic Low Level Startup:
ERROR while reading /usr/local/tomcat/content/erddap/setup.xml:
java.lang.RuntimeException:
ERROR in Test.ensureTrue:
bigParentDirectory (/erddapData/) doesnt exist.
 at com.cohort.util.Test.error(Test.java:43)
 at com.cohort.util.Test.ensureTrue(Test.java:71)
 at gov.noaa.pfel.erddap.util.EDStatic.<clinit>(EDStatic.java:1756)
 at gov.noaa.pfel.erddap.Erddap.<init>(Erddap.java:223)

```

this is odd as i can go to that location within the container
```shell
# ls /
bin   dev            erddapData  home  lib64  mnt  proc  run   srv  tmp  var
boot  entrypoint.sh  etc         lib   media  opt  root  sbin  sys  usr
# ls /erddapData/
badFilesFlag         dataset       hardFlag             subscriptionsV1ArchivedAt2021-10-11T13.27.25.txt
cache                decompressed  logs                 subscriptionsV1ArchivedAt2021-10-11T13.59.10.txt
copy                 erddap        lucene               subscriptionsV1ArchivedAt2021-10-11T14.06.21.txt
currentDatasets.xml  flag          subscriptionsV1.txt  subscriptionsV1ArchivedAt2022-03-30T11.19.01.txt
#
```

This isn't the only issue with config.sh as i have noticed that if i remove that variable and set another 
```shell
ERDDAP_adminInstitutionUrl="https://www.example.ac.uk"
```
we get an error of 
```shell
////**** EDStatic Low Level Startup
localTime=2022-03-30T12:59:51+00:00
erddapVersion=2.18
Java 1.8.0_322 (64 bit, Oracle Corporation) on Linux (5.10.16.3-microsoft-standard-WSL2).
MemoryInUse=   568 MB (highWaterMark=   568 MB) (Xmx ~= 4012 MB)
logLevel=info: verbose=true reallyVerbose=false
got bigParentDirectory from ERDDAP_bigParentDirectory
got emailFromAddress from ERDDAP_emailFromAddress
got emailEverythingTo from ERDDAP_emailEverythingTo
ERROR in File2.deleteIfOld: dir=/erddapData/dataset/_FileVisitor/ isnt a directory.
bigParentDirectory=/erddapData/
webInfParentDirectory=/usr/local/tomcat/webapps/erddap/
java.awt.HeadlessException
 at gov.noaa.pfel.coastwatch.sgt.SgtUtil.isBufferedImageAccelerated(SgtUtil.java:368)
 at gov.noaa.pfel.erddap.util.EDStatic.<clinit>(EDStatic.java:1830)
 at gov.noaa.pfel.erddap.Erddap.<init>(Erddap.java:223)


bufferedImage isAccelerated=[unknown]
got baseHttpsUrl from ERDDAP_baseHttpsUrl
got adminInstitution from ERDDAP_adminInstitution
got adminInstitutionUrl from ERDDAP_adminInstitutionUrl
got adminIndividualName from ERDDAP_adminIndividualName
got adminPosition from ERDDAP_adminPosition
got adminPhone from ERDDAP_adminPhone
got adminAddress from ERDDAP_adminAddress
got adminCity from ERDDAP_adminCity
got adminStateOrProvince from ERDDAP_adminStateOrProvince
got adminPostalCode from ERDDAP_adminPostalCode
got adminCountry from ERDDAP_adminCountry
got adminEmail from ERDDAP_adminEmail
ERROR during EDStatic Low Level Startup:
ERROR while reading /usr/local/tomcat/content/erddap/setup.xml:
java.lang.RuntimeException: setup.xml error: invalid <adminInstitutionUrl>=https://www.example.ac.uk
 at gov.noaa.pfel.erddap.util.EDStatic.<clinit>(EDStatic.java:1940)
 at gov.noaa.pfel.erddap.Erddap.<init>(Erddap.java:223)
```

any help or pointers on further debugging would be very much appreciated

**Comment by kwilcox** [comment]
Could you post the complete log when using the `2.18` image: `axiom/docker-erddap:2.18`? You should see some debug messages like _"ERDDAP configured with: ..."_ and _"ERDDAP Running with: ..."_

**Comment by thogar-computer** [comment]
sure the output is 
```shell
ERDDAP configured with: ERDDAP_CONTENT_URL=https://github.com/BobSimons/erddap/releases/download/v2.18/erddapContent.zip
ERDDAP_VERSION=2.18
ERDDAP_WAR_URL=https://github.com/BobSimons/erddap/releases/download/v2.18/erddap.war
ERDDAP_adminAddress=123 Irrelevant St.
ERDDAP_adminCity=Nowhere
ERDDAP_adminCountry=USA
ERDDAP_adminEmail=nobody@example.com
ERDDAP_adminIndividualName=Axiom Docker Install
ERDDAP_adminInstitution=Axiom Docker Install
ERDDAP_adminInstitutionUrl=https://www.example.ac.uk
ERDDAP_adminPhone=555-555-5555
ERDDAP_adminPosition=Software Engineer
ERDDAP_adminPostalCode=99504
ERDDAP_adminStateOrProvince=AK
ERDDAP_baseHttpsUrl=https://localhost:8443
ERDDAP_bigParentDirectory=/erddapData
ERDDAP_emailDailyReportsTo=nobody@example.com
ERDDAP_emailEverythingTo=nobody@example.com
ERDDAP_emailFromAddress=nothing@example.com
ERDDAP_emailPassword=
ERDDAP_emailProperties=
ERDDAP_emailSmtpHost=
ERDDAP_emailSmtpPort=
ERDDAP_emailUserName=
ERDDAP_flagKeyKey=73976bb0-9cd4-11e3-a5e2-0800200c9a66
ERDDAP Running with:  -server -d64 -Xms4G -Xmx4G -XX:+HeapDumpOnOutOfMemoryError -Djava.awt.headless=true -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -DerddapContentDirectory=/usr/local/tomcat/content/erddap/ -Djna.tmpdir=/tmp/ -Djava.security.egd=file:/dev/./urandom
01-Apr-2022 07:00:36.434 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version name:   Apache Tomcat
01-Apr-2022 07:00:36.436 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Jan 17 2022 22:07:47 UTC
01-Apr-2022 07:00:36.436 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version number: 8.5.75.0
01-Apr-2022 07:00:36.437 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
01-Apr-2022 07:00:36.438 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            5.10.16.3-microsoft-standard-WSL2
01-Apr-2022 07:00:36.438 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
01-Apr-2022 07:00:36.439 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/local/openjdk-8/jre
01-Apr-2022 07:00:36.439 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.8.0_322-b06
01-Apr-2022 07:00:36.439 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
01-Apr-2022 07:00:36.439 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /usr/local/tomcat
01-Apr-2022 07:00:36.440 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/local/tomcat
01-Apr-2022 07:00:36.440 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/usr/local/tomcat/conf/logging.properties
01-Apr-2022 07:00:36.441 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
01-Apr-2022 07:00:36.441 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xms4G
01-Apr-2022 07:00:36.441 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xmx4G
01-Apr-2022 07:00:36.442 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:+HeapDumpOnOutOfMemoryError
01-Apr-2022 07:00:36.442 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.awt.headless=true
01-Apr-2022 07:00:36.446 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:+UseConcMarkSweepGC
01-Apr-2022 07:00:36.447 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:+CMSClassUnloadingEnabled
01-Apr-2022 07:00:36.447 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -DerddapContentDirectory=/usr/local/tomcat/content/erddap/
01-Apr-2022 07:00:36.447 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djna.tmpdir=/tmp/
01-Apr-2022 07:00:36.447 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.security.egd=file:/dev/./urandom
01-Apr-2022 07:00:36.448 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
01-Apr-2022 07:00:36.448 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
01-Apr-2022 07:00:36.448 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
01-Apr-2022 07:00:36.448 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
01-Apr-2022 07:00:36.448 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/usr/local/tomcat
01-Apr-2022 07:00:36.449 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/local/tomcat
01-Apr-2022 07:00:36.449 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/usr/local/tomcat/temp
01-Apr-2022 07:00:36.449 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Loaded Apache Tomcat Native library [1.2.31] using APR version [1.7.0].
01-Apr-2022 07:00:36.449 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true], UDS [{4}].
01-Apr-2022 07:00:36.449 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
01-Apr-2022 07:00:36.455 INFO [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL successfully initialized [OpenSSL 1.1.1k  25 Mar 2021]
01-Apr-2022 07:00:36.543 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
01-Apr-2022 07:00:36.562 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
01-Apr-2022 07:00:36.581 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 712 ms
01-Apr-2022 07:00:36.641 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
01-Apr-2022 07:00:36.642 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet engine: [Apache Tomcat]
01-Apr-2022 07:00:36.660 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/erddap]
01-Apr-2022 07:00:41.232 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
01-Apr-2022 07:00:41.276 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/erddap] has finished in [4,617] ms
01-Apr-2022 07:00:41.280 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
01-Apr-2022 07:00:41.290 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 4708 ms
```

i am running windows 10 and using docker for desktop via wsl 

interestingly 2.18 works and i can see the erddap page (even when using the config.sh)

i have checked without the version number and it still fails with the above error

**Comment by thogar-computer** [comment]
```shell
docker run -p 8088:8080 -v C:\docker\erddap-docker-setup\config2.sh:/usr/local/tomcat/bin/config.sh -v C:\docker\volumes\erddap\BigDataDir:/erddapData  axiom/docker-erddap
/usr/local/tomcat/bin/config.sh: line 2: $'\r': command not found
ERDDAP configured with: ERDDAP_CONTENT_URL=https://github.com/BobSimons/erddap/releases/download/v2.18/erddapContent.zip
ERDDAP_VERSION=2.18
ERDDAP_WAR_URL=https://github.com/BobSimons/erddap/releases/download/v2.18/erddap.war
ERDDAP_adminAddress=123 Irrelevant St.
ERDDAP_adminCity=Nowhere
ERDDAP_adminCountry=USA
ERDDAP_adminEmail=nobody@example.com
ERDDAP_adminIndividualName=Axiom Docker Install
ERDDAP_adminInstitution=Axiom Docker Install
ERDDAP_adminInstitutionUrl=https://github.com/axiom-data-science/docker-erddap
ERDDAP_adminPhone=555-555-5555
ERDDAP_adminPosition=Software Engineer
ERDDAP_adminPostalCode=99504
ERDDAP_adminStateOrProvince=AK
ERDDAP_baseHttpsUrl=https://localhost:8443
ERDDAP_bigParentDirectory=/erddapData
ERDDAP_emailDailyReportsTo=nobody@example.com
ERDDAP_emailEverythingTo=nobody@example.com
ERDDAP_emailFromAddress=nothing@example.com
ERDDAP_emailPassword=
ERDDAP_emailProperties=
ERDDAP_emailSmtpHost=
ERDDAP_emailSmtpPort=
ERDDAP_emailUserName=
ERDDAP_flagKeyKey=73976bb0-9cd4-11e3-a5e2-0800200c9a66
ERDDAP Running with:  -server -d64 -Xms4G -Xmx4G -XX:+HeapDumpOnOutOfMemoryError -Djava.awt.headless=true -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -DerddapContentDirectory=/usr/local/tomcat/content/erddap/ -Djna.tmpdir=/tmp/ -Djava.security.egd=file:/dev/./urandom
01-Apr-2022 07:08:46.275 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version name:   Apache Tomcat
01-Apr-2022 07:08:46.276 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Jan 17 2022 22:07:47 UTC
01-Apr-2022 07:08:46.277 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version number: 8.5.75.0
01-Apr-2022 07:08:46.277 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
01-Apr-2022 07:08:46.277 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            5.10.16.3-microsoft-standard-WSL2
01-Apr-2022 07:08:46.277 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
01-Apr-2022 07:08:46.277 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/local/openjdk-8/jre
01-Apr-2022 07:08:46.278 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.8.0_322-b06
01-Apr-2022 07:08:46.278 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
01-Apr-2022 07:08:46.278 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /usr/local/tomcat
01-Apr-2022 07:08:46.278 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/local/tomcat
01-Apr-2022 07:08:46.279 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/usr/local/tomcat/conf/logging.properties
01-Apr-2022 07:08:46.279 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
01-Apr-2022 07:08:46.280 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xms4G
01-Apr-2022 07:08:46.280 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xmx4G
01-Apr-2022 07:08:46.280 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:+HeapDumpOnOutOfMemoryError
01-Apr-2022 07:08:46.280 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.awt.headless=true
01-Apr-2022 07:08:46.284 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:+UseConcMarkSweepGC
01-Apr-2022 07:08:46.284 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:+CMSClassUnloadingEnabled
01-Apr-2022 07:08:46.284 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -DerddapContentDirectory=/usr/local/tomcat/content/erddap/
01-Apr-2022 07:08:46.284 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djna.tmpdir=/tmp/
01-Apr-2022 07:08:46.284 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.security.egd=file:/dev/./urandom
01-Apr-2022 07:08:46.285 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
01-Apr-2022 07:08:46.285 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
01-Apr-2022 07:08:46.285 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
01-Apr-2022 07:08:46.285 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
01-Apr-2022 07:08:46.285 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/usr/local/tomcat
01-Apr-2022 07:08:46.285 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/local/tomcat
01-Apr-2022 07:08:46.286 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/usr/local/tomcat/temp
01-Apr-2022 07:08:46.286 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Loaded Apache Tomcat Native library [1.2.31] using APR version [1.7.0].
01-Apr-2022 07:08:46.286 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true], UDS [{4}].
01-Apr-2022 07:08:46.286 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
01-Apr-2022 07:08:46.290 INFO [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL successfully initialized [OpenSSL 1.1.1k  25 Mar 2021]
01-Apr-2022 07:08:46.355 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
01-Apr-2022 07:08:46.369 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
01-Apr-2022 07:08:46.382 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 500 ms
01-Apr-2022 07:08:46.414 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
01-Apr-2022 07:08:46.414 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet engine: [Apache Tomcat]
01-Apr-2022 07:08:46.424 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/erddap]
01-Apr-2022 07:08:50.141 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
01-Apr-2022 07:08:50.175 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/erddap] has finished in [3,752] ms
01-Apr-2022 07:08:50.179 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
01-Apr-2022 07:08:50.188 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 3805 ms

////**** EDStatic Low Level Startup
localTime=2022-04-01T07:09:19+00:00
erddapVersion=2.18
Java 1.8.0_322 (64 bit, Oracle Corporation) on Linux (5.10.16.3-microsoft-standard-WSL2).
MemoryInUse=   559 MB (highWaterMark=   559 MB) (Xmx ~= 4012 MB)
logLevel=info: verbose=true reallyVerbose=false
got bigParentDirectory from ERDDAP_bigParentDirectory
ERROR during EDStatic Low Level Startup:
ERROR while reading /usr/local/tomcat/content/erddap/setup.xml:
java.lang.RuntimeException:
ERROR in Test.ensureTrue:
bigParentDirectory (/erddapData/) doesn't exist.
 at com.cohort.util.Test.error(Test.java:43)
 at com.cohort.util.Test.ensureTrue(Test.java:71)
 at gov.noaa.pfel.erddap.util.EDStatic.<clinit>(EDStatic.java:1756)
 at gov.noaa.pfel.erddap.Erddap.<init>(Erddap.java:223)
```

**Comment by kwilcox** [comment]
I think I can see two issues:

1. The `config.sh` file you are bind mounting into the container is not working correctly.
    I see a reference to `\r` in your logs. Can you make sure to save your `config2.sh` file with linux line endings (`\n`) and not windows line endings (`\r\n`)?

2. The `bigParentDirectory` directory you are bind mounting into the container is not working correctly.
    I don't have a windows computer to test this, maybe try quoting your host's volume path and making sure the directory exists on the host before running?
    ```
    docker run -p 8088:8080 -v "C:\docker\erddap-docker-setup\config2.sh":/usr/local/tomcat/bin/config.sh -v "C:\docker\volumes\erddap\BigDataDir\":/erddapData  axiom/docker-erddap:2.18
    ```

**Comment by kwilcox** [comment]
@thogar-computer Did you figure this out?

**Comment by kwilcox** [comment]
Closing, please comment if this is still an issue and I will re-open.
